# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax
name: 'generate-reports'
description: 'GitHub Action that generates Minecraft default reports.'
author: 'Mqxx'
branding:
  icon: 'file'
  color: 'green'

inputs:
  version: 
    description: |
      Version to generate data for.

      Possible values:
      - 'latest-snapshot'
      - 'latest-release'
      - <valid_version> (ex. 1.21.11 or 26.1-snapshot-1)
      
    required: false
    default: 'latest-release'

  manifest-url:
    description: 'URL to the manifest API.'
    required: false
    default: 'https://piston-meta.mojang.com/mc/game/version_manifest_v2.json'

  if-version-is-invalid:
    description: |
      The desired behavior if the provided version is invalid.

      Possible values:
      - 'warn': Output a warning but do not fail the action
      - 'error': Fail the action with an error message
      - 'ignore': Do not output any warnings or errors, the action does not fail
    required: false
    default: 'warn'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_VERSION: ${{ inputs.version }}
    INPUT_MANIFEST_URL: ${{ inputs.manifest-url }}
    INPUT_IF_VERSION_IS_INVALID: ${{ inputs.if-version-is-invalid }}
